#pragma once

#include "core/Core.h"
#include "core/Application.h"

#ifndef TESTBED
//#include "EntryPoint.h"
#endif

//sge
#include "core/ApplicationConstants.h"
#include "runtime/Context.h"
#include "core/Window.h"
#include "geometry/Mesh.h"
#include "render/Shader.h"
#include "component/Transformation.h"
#include "render/Material.h"
#include "texture/Texture.h"
#include "lights/Light.h"
#include "lights/DirectionalLight.h"
#include "lights/PointLight.h"
#include "camera/ICamera.h"
#include "runtime/Scene.h"
#include "systems/Skybox.h"
#include "ui/Input.h"
#include "ui/Keyboard.h"
#include "ui/Mouse.h"
#include "core/EventSystem.h"
#include "geometry/Quad.h"
#include "geometry/Box.h"
#include "geometry/Sphere.h"
#include "core/Configurations.h"
#include "geometry/ModelImporter.h"
#include "memory/ResourceWrapper.h"
#include "runtime/Entity.h"
#include "geometry/ShapeFactory.h"
#include "component/Component.h"
#include "core/Random.h"
#include "systems/TimeManager.h"
#include "render/Graphics.h"

#include "memory/ResourceManager.h"
#include "systems/ObjectPicker.h"
#include "physics/Physics.h"
#include "memory/Assets.h"
#include "serialize/Archiver.h"
#include "animation/AnimationLoader.h"
#include "core/System.h"
#include "utils/DebugHelper.h"
#include "systems/WaterSystem.h"
#include "systems/VolumetricCloudsSystem.h"
#include "systems/UniqueNameManager.h"
#include "render/RenderCommand.h"
#include "camera/CameraControllerFreeLook.h"

#include "animation/Animator.h"
#include "component/Terrain.h"
#include "component/PhysicsComponent.h"
#include "component/MeshRendererComponent.h"
#include "component/ShaderComponent.h"
#include "component/ObjectComponent.h"
#include "component/NativeScriptComponent.h"
#include "component/RenderableComponent.h"
#include "component/SkyboxComponent.h"
#include "component/PlayerControllerComponent.h"
#include "component/ScriptComponent.h"
#include "component/ImageComponent.h"
#include "component/PostProcessComponent.h"
#include "component/WaterBodyComponent.h"
#include "component/VolumeComponent.h"
#include "component/VolumetricCloudsComponent.h"

#include "runtime/Prefab.h"
#include "memory/BuiltInAssets.h"

#include "fileSystem/WorkingDirectory.h"
#include "fileSystem/ScopedPath.h"
#include "core/GUILayer.h"
#include "component/TexturePainter.h"

#include "utils/Math3D.h"
